spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    url: jdbc:mysql://localhost:3306/integration_test?serverTimezone=UTC
    username: root
    password: 2529428523
    driver-class-name: com.mysql.jdbc.Driver